FROM militarpancho1/sonar-scanner:latest

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -

RUN apt-get update && apt-get install -y nodejs

RUN npm install typescript
ENV NODE_PATH /src/node_modules

ENTRYPOINT sonar-scanner \
  -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
  -Dsonar.sources=. \
  -Dsonar.host.url=${SONAR_HOST} \
  -Dsonar.login=${SONAR_TOKEN} \
  -Dsonar.javascript.lcov.reportPaths=${SONAR_TS_REPORTPATH}
