FROM militarpancho1/sonar-scanner:latest

RUN apt-get update && apt-get -y install pylint

ENTRYPOINT sonar-scanner \
  -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
  -Dsonar.sources=. \
  -Dsonar.host.url=${SONAR_HOST} \
  -Dsonar.login=${SONAR_TOKEN} \
  -Dsonar.python.coverage.reportPaths=${SONAR_PY_REPORTPATH} \
  -Dsonar.projectVersion=${COMMIT_VERSION}