FROM militarpancho1/sonar-scanner:latest

RUN apt-get install npm

RUN npm install typescript
ENV NODE_PATH /src/node_modules

ENTRYPOINT sonar-scanner \
  -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
  -Dsonar.sources=. \
  -Dsonar.host.url=${SONAR_HOST} \
  -Dsonar.login=${SONAR_TOKEN} \
  -Dsonar.javascript.lcov.reportPaths=${SONAR_TS_REPORTPATH} \
  -Dsonar.projectVersion=${COMMIT_VERSION}